services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - FIREBASE_ADMIN_SDK=/app/studybuds-firebase-adminsdk.json
    volumes:
      - ./backend:/app
      - ./backend/studybuds-firebase-adminsdk.json:/app/studybuds-firebase-adminsdk.json
    command: npm run start

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    command: npm start
